[package]
name = "double_proof_of_work"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.1"
rand = "0.8.5"
sha3 = "0.10.1"

[features]
reasonably-fast = []
bad-idea = []
